# Check for a .configured file generated by configure script
ifeq ($(wildcard .configured),)
$(error You must run `./configure` before you can build.)
endif

RC = rustc
RFLAGS = -C opt-level=3
BIN = bin/dproc
BINDIR = bin
SRC = src/main.rs
PREFIX ?= /usr/local

all: build

build: src/*
	mkdir -p bin
	$(RC) $(RFLAGS) $(SRC) -o $(BIN)
	
clean:
	rm -rf $(BINDIR)
	
install:
	mkdir -p $(PREFIX)/$(BINDIR)
	rm -rf $(PREFIX)/$(BIN)
	cp $(BIN) $(PREFIX)/$(BIN)
	
uninstall:
	rm -rf $(PREFIX)/$(BIN)

.PHONY: all build clean install uninstall
